[tool.poetry]
name = "accidentdetection_lv2"
version = "0.1.0"
description = ""
authors = ["suhyun.kim <suhyun.kim@42dot.ai>"]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
jupyter = "^1.0.0"
torch = "^1.13.1"
<<<<<<< Updated upstream
pandas = "^1.5.2"
numpy = "^1.24.1"
jupyterlab = "^3.5.2"
=======
pandas = "^1.5.3"
matplotlib = "^3.6.3"
tqdm = "^4.64.1"
scikit-learn = "^1.2.1"
tensorboard = "^2.11.2"
ipykernel = "^6.21.1"
python-dotenv = "^0.21.1"
boto3 = "^1.26.68"
google-cloud-storage = "^2.7.0"
google-cloud = "^0.34.0"
pre-commit = "^3.0.4"
GitPython = "^3.1.30"
NavPy = "^1.0"
jupyter-contrib-nbextensions = "^0.7.0"
tensorflow-macos = "^2.11.0"
>>>>>>> Stashed changes

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
